### ISSUE TITLE
Various small frontend bugs

### ISSUE THREAD

**Issue by tomatocat** [googleinterns/step119-2020#34]
**Describe the bug**
- [x] completed games are not rendered in the dashboard cards (probable due to index OOB error)
- [x] game page displays game ID instead of game name
- [x] email verification should link to deployment website instead of localhost
- [x] game page should have a button to copy game invite id or link
- [x] after game creation, redirect to that game's page instead of the dashboard
- [x] after game join, redirect to that game's page instead of the dashboard
- [x] make sure users can't join the same game twice
- [x] make sure users can't join games that have already ended

**Screenshots**
None, feel free to add

**Additional context**
Mostly from Tony's email after MVP presentation. Feel free to move into separate individual issues if anything seems too big to be compiled here.

**Comment by pl98** [comment]
@tomatocat do you want to fix the OOB error from the canvas component, or should I fix it on my end?

**Comment by tomatocat** [comment]
I think this relates to the dashboard cards on your end. Once the index is equal to the size of the player array, we know the game is over. In that case we should directly display on the card that the game is ending without even entering the logic that tries to index into the player array.
